name: Cypress End to End Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies and Run
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 manage.py runserver 0.0.0.0:8000

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: ls -l
    - run: cd client
    - run: npm install
    - run: npm run build
    - run: npm run int-test
